spring:
  application:
    name: cctv
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/cctvdb
    username: root
    password: 01080823424
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  logging:
    level:
      root: DEBUG
      cctv: DEBUG
      org.springframework.security: DEBUG
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 구글 클라이언트 키
            client-secret: 구글 클라이언트 비밀번호
            scope: email, profile
          naver:
            client-id: EJClaLidIH_PyzPh4erX
            client-secret: 4cSb3zWrao
            redirect-uri: http://localhost:8080/naver
            authorization-grant-type: authorization_code
            client-name: Naver
            scope: name, email, profile_image

          kakao:
            client-id: f768ba6915a8b6719ac46d7646324cdd
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            client-secret: 1NhgtpmqAbSrdCQug2nTejwjsfLQr7eg
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: profile_nickname, profile_image, account_email
            client-name: Kakao

        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response

          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
